apiVersion: v1
kind: Service
metadata:
  name: {{ include "boilerplate.fullname" . }}
  labels:
    {{- include "boilerplate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: infra
      port: 8081
      targetPort: infra
      protocol: TCP
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "boilerplate.selectorLabels" . | nindent 4 }}
