name: caprover

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install caprover
      run: npm install -g caprover

    - name: Caprover Deploy
      run: caprover deploy -h 'https://captain.ravilushqa.dev' -p '${{ secrets.CAPROVER_PASSWORD }}' -i 'ghcr.io/${{ github.actor }}/boilerplate:latest' -a 'boilerplate'