name: caprover

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        uses: AlexxNB/caprover-action@v1
        with:
          server: 'https://captain.ravilushqa.dev'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appname: 'boilerplate'