on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
env:
  # Path to where test results will be saved.
  TEST_RESULTS: /tmp/test-results
  # Default minimum version of Go to support.
  DEFAULT_GO_VERSION: 1.18

name: Test
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Module cache
        uses: actions/cache@v3
        env:
          cache-name: go-mod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
      - name: Run coverage tests
        run: |
          make test-coverage
          mkdir $TEST_RESULTS
          cp coverage.out $TEST_RESULTS
          cp coverage.txt $TEST_RESULTS
          cp coverage.html $TEST_RESULTS
      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: true
      - name: Store coverage test output
        uses: actions/upload-artifact@v3
        with:
          name: boilerplate-go-test-output
          path: ${{ env.TEST_RESULTS }}
  compatibility-test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test ./...

  test-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - run: go test ./...